CREATE TABLE contas (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SALDO NUMERIC(12, 2) DEFAULT 0
);

CREATE TABLE transferencias(
    ID BIGSERIAL PRIMARY KEY,
    IDEMPOTENCY_KEY VARCHAR(255) UNIQUE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ,
    TIPO VARCHAR(20) NOT NULL,
    CONTA_ID BIGINT NOT NULL,
    VALOR NUMERIC(12, 2) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,

    CONSTRAINT fk_conta FOREIGN KEY (CONTA_ID) REFERENCES contas(ID) ON DELETE CASCADE
);
